### ISSUE TITLE
Buttons on the toolbar when replying to a comment not working

### ISSUE THREAD

**Issue by jalsol** [VNOI-Admin/OJ#225]
**UPDATE**: The bug mentioned happens to all buttons on the toolbar. I will still keep the rest of the report to the Image button to act as an example.

**Describe the bug**
![](https://i.ibb.co/HTkvCrR/image.png)

This button does **not** open a pop-up to paste the image URL as expected.
**Note**: The button does not work only when replying to another comment (the title underlined being "*Replying to comment*"). It behaves normally when creating a new comment.

**To Reproduce**
1. Go to any existing comment, and click on the Reply button
2. Click on the Image button

**Expected behavior**
The following pop-up to allow entering the image URL should appear.

![](https://i.ibb.co/pX1zYDM/image.png)

**Comment by jalsol** [comment]
I've just found out that this applies for every button on the toolbar, not just the Image button (as long as it's replying to an existing comment).

**Comment by ngkan** [comment]
This bug is replicable on [DMOJ website](https://dmoj.ca/). You should create an issue in the original [repo](https://github.com/DMOJ/online-judge).
