### ISSUE TITLE
"Hide problems I've solved" box does not work

### ISSUE THREAD

**Issue by jalsol** [VNOI-Admin/OJ#227]
**Describe the bug**
On the Statistic tab of another user's page, the "Hide problems I've solved" box does not hide problems I have solved.

**To Reproduce**
1. Go to a user's profile
2. Click on "Statistic"
3. Check "Hide problems I've solved"
4. Page gets reloaded, the query string "hide_solved=1" appears but nothing changes otherwise.

**Expected behavior**
Problems that I have solved should be hidden after the box is checked.

**Screenshots**

![Box unchecked, problem appears](https://i.ibb.co/dBbb6fd/image.png)
<p align="center">Box unchecked, problem appears</p>

![Box checked, problem still appears](https://i.ibb.co/G2sN0q1/image.png)
<p align="center">Box checked, problem still appears</p>

![Problem solved by user](https://i.ibb.co/Thv2jNL/image.png)
<p align="center">Problem solved by user</p>

**Desktop:**
 - OS: Archcraft (5.10.88-2-lts)
 - Browser: Brave Browser / Mozilla Firefox
 - Version: 96.1.34.53 beta / 95.0.2
 
 **Additional context**
Tested on both normal and Incognito mode of both browsers.

**Comment by leduythuccs** [comment]
The purpose of the Hide checkbox is to hide the problems in the list at the bottom of the page, not the problems inside the performance table:

![image](https://user-images.githubusercontent.com/23715841/148645078-ba31c504-a39c-4876-b880-2a131146db94.png)
