### ISSUE TITLE
Create organization list of Vietnamese universities and add org filter for submissions

### ISSUE THREAD

**Issue by liv1n9** [VNOI-Admin/OJ#28]
We are creating a competitive programing group of PTIT and want to use VNOJ for practicing and we want to track progress of our members in VNOJ. So it would be great if we can choose our university from affiliated organizations list and filter our member in each problem's submission history.

**Comment by leduythuccs** [comment]
We (VNOI team) are planning to create organizations for universities & high schools in Vietnam. However, it is not a high priority because we are having higher priority things to do right now.

However, it will be done as soon as we finish our higher priority things. Thank you for your suggestion.

**Comment by leduythuccs** [comment]
Hi, I created PTIT org, please check out it at https://oj.vnoi.info/organization/3-PTIT. 

I haven't found a better logo of your uni, if you have the better one, please send me the link.

**Comment by liv1n9** [comment]
@leduythuccs Hi, thank you and VNOI dev team for this feature, it will help a lot. About the logo, you've been using the best version already :), so no need to change for now

**Comment by leduythuccs** [comment]
Hi, I added a field in the search form to filter submission in a org: 
![image](https://user-images.githubusercontent.com/23715841/116774025-b2139e80-aa83-11eb-968a-3d976a9fe020.png)

You can checkout PTIT submissions here: https://oj.vnoi.info/submissions/?organization=3
I will close this issue, feel free to re-open it or open a new one if you have any problem.
