### ISSUE TITLE
SIGSEGV: invalid_state trang lỗi /admin/judge/profile/add/ site: fatal signal: Segmentation fault site died (signal 500, exit -11)

### ISSUE THREAD

**Issue by HVThangQBU** [VNOI-Admin/OJ#342]
File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 197, in __get__
    raise self.RelatedObjectDoesNotExist(
judge.models.profile.Profile.user.RelatedObjectDoesNotExist: Profile has no user.

**Comment by leduythuccs** [comment]
This is because you add the user by the admin panel so the `User` instance has not been created a long with the Profile that cause the issue

Advice 1: don't do that again

Advice 2: Good luck
