### ISSUE TITLE
Gặp lỗi Bad Gateway khi gửi email Quên mật khẩu

### ISSUE THREAD

**Issue by duongnotnhan** [VNOI-Admin/OJ#379]
![image](https://github.com/VNOI-Admin/OJ/assets/98535924/a4c69af1-597b-4032-bc04-78fde3231be1)
![image](https://github.com/VNOI-Admin/OJ/assets/98535924/0f222cbe-e911-43f0-8c8e-534a87fa30bf)

_**Đã đảm bảo việc email đã tồn tại trong một tài khoản của trang**_

## Thông tin hệ thống
- **Linux: Ubuntu 22.04 TLS**
- Chạy website bằng **Docker image** (đã có chỉnh sửa /repo lên bản mới nhất)

**Comment by theadanielskocher** [comment]
Cho em hỏi là làm sao để đổi được màu của thanh taskbar vậy ạ. Em thử chỉnh sửa ở file `.scss` mà không có tác dụng ạ, em cảm ơn.

**Comment by duongnotnhan** [comment]
> Cho em hỏi là làm sao để đổi được màu của thanh taskbar vậy ạ. Em thử chỉnh sửa ở file `.scss` mà không có tác dụng ạ, em cảm ơn.

Mình cũng có thử sửa lại và không hoạt động, nhưng khi mình cài đặt lại trang từ đầu, chỉnh sửa trước khi chạy site thì nó đã hoạt động.

**Comment by theadanielskocher** [comment]
Hiện tại em đã biết cách làm rồi ạ, em chia sẻ lên đây luôn:
1. run `$ ./scripts/copy_static` in the terminal
2. restart the docker compose (`$ docker compose restart`)
