### ISSUE TITLE
Error when running pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by EricArita** [VNOI-Admin/OJ#38]
Hi all,

I'm following the setup instruction of DMOJ to setup on source VNOJ but when I ran command 'pip3 install -r requirements.txt', I got an error in the following image: 

![image](https://user-images.githubusercontent.com/30250345/115567947-fd8cb680-a2e5-11eb-95e7-b6a07540bb69.png)

I'm not good at Python so I don't know this error is a bug or my setup was wrong in any step. Please help me!

**Comment by leduythuccs** [comment]
Please try again with `--no-cache-dir` option: `python3 -m pip --no-cache-dir install -r requirements.txt`

**Comment by EricArita** [comment]
I've tried your command but it throws a new error releated to version

![image](https://user-images.githubusercontent.com/30250345/115572513-2c0c9080-a2ea-11eb-9944-7193572a0425.png)

**Comment by hung3a8** [comment]
I think you should manually check your connection between your machine the pypi server. The URL can still be accessed from the outside. Check it with your browser. If the browser returns error, check your internet connection and firewall if there is any settings that prevent the request process.

**Comment by EricArita** [comment]
Thank all you guys for your support, I will try to fix by the solution of @hung3a8 and let u know the result soon.

BTW: @leduythuccs  Do you think we should have discussion area opened on this repo to support conveniently Q&A for everyone (or any other channels)? Now I'm doing a project related to my college, and we want to setup and integrate your VNOJ system as a service in our one that serves for judging code of student. So it will be so great if I can contact or ask you or your team for support whenever I get a problem

**Comment by ngkan** [comment]
Upgrading pip inside the venv to the latest version should fix the problem.
