### ISSUE TITLE
Live update not filter submission in contest view

### ISSUE THREAD

**Issue by leduythuccs** [VNOI-Admin/OJ#69]
The live update is not working as expected. [This page](https://oj.vnoi.info/contest/tt3dh2021/submissions/) can show the submissions that are not in the contest. 
![image](https://user-images.githubusercontent.com/23715841/118288241-6b4f8b00-b4fe-11eb-82bb-ba82df7634d1.png)

We can fix it by get the contest id of the view instead of the request in this line: [templates/submission/list.html#L6](https://github.com/VNOI-Admin/OJ/blob/master/templates/submission/list.html#L6)

**Comment by ngkan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [contest notification](https://trello.com/c/1jxLLATr/78-contest-notification)

**Comment by leduythuccs** [comment]
Waiting for DMOJ to fix sync this is not much high priority

**Comment by leduythuccs** [comment]
As far as i know, this fixed by 528b5c9bab3d4052b9d2b235bc658d2a7025ecdf
