### ISSUE TITLE
Users occasionally post code in the comment section with current UI

### ISSUE THREAD

**Issue by ngkan** [VNOI-Admin/OJ#77]
Lots of online judges have a code window under the problem statement of a problem, whereas our UI have a comment window instead. People would just simple copy+paste their code into the comment window without noticing the window is for commenting.

**Comment by leduythuccs** [comment]
Should we put a code window between the problem window and the comment window?

**Comment by hieplpvip** [comment]
Mitigated in https://github.com/VNOI-Admin/OJ/pull/201
